export const data = [
  {
    craftable_id: 1,
    craftable_name: '  Maple Lumber\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Lumber',
    craftable_recipe_yield: 1,
    craftable_durability: 40,
    craftable_difficulty: 9,
    craftable_max_quality: 80,
  },
  {
    craftable_id: 2,
    craftable_name: '  Larboard Hull Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 40,
    craftable_difficulty: 9,
    craftable_max_quality: 100,
  },
  {
    craftable_id: 3,
    craftable_name: '  Bladder Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 19,
    craftable_max_quality: 100,
  },
  {
    craftable_id: 4,
    craftable_name: '  Hull Interior Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 19,
    craftable_max_quality: 100,
  },
  {
    craftable_id: 5,
    craftable_name: '  Maple Clogs\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Feet',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 19,
    craftable_max_quality: 100,
  },
  {
    craftable_id: 6,
    craftable_name: '  Starboard Hull Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 19,
    craftable_max_quality: 100,
  },
  {
    craftable_id: 7,
    craftable_name: '  Bladder Lining Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '1',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 28,
    craftable_max_quality: 75,
  },
  {
    craftable_id: 8,
    craftable_name: '  Maple Shortbow\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '2',
    craftable_type: "Archer's Arm",
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 20,
    craftable_max_quality: 110,
  },
  {
    craftable_id: 9,
    craftable_name: '  Engine Casing Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 40,
    craftable_difficulty: 10,
    craftable_max_quality: 120,
  },
  {
    craftable_id: 10,
    craftable_name: '  Bone Harpoon\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: "Lancer's Arm",
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 20,
    craftable_max_quality: 120,
  },
  {
    craftable_id: 11,
    craftable_name: '  Gyrodrive Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 20,
    craftable_max_quality: 120,
  },
  {
    craftable_id: 12,
    craftable_name: '  Crafting Tool Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 30,
    craftable_max_quality: 90,
  },
  {
    craftable_id: 13,
    craftable_name: '  Deck Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 30,
    craftable_max_quality: 90,
  },
  {
    craftable_id: 14,
    craftable_name: '  Propulsion Engine Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 30,
    craftable_max_quality: 90,
  },
  {
    craftable_id: 15,
    craftable_name: '  Rigging Component\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '3',
    craftable_type: 'Other',
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 36,
    craftable_max_quality: 60,
  },
  {
    craftable_id: 16,
    craftable_name: '  Amateurs Grinding Wheel\n',
    craftable_profession: 'Carpenter',
    craftable_recipe_req_level: '4',
    craftable_type: "Goldsmith's Secondary Tool",
    craftable_recipe_yield: 1,
    craftable_durability: 60,
    craftable_difficulty: 21,
    craftable_max_quality: 130,
  },
]
